version: '3'
services:
  frontend-flaskpress:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend-flaskpress
    networks:
      - app-network

  backend-flaskpress:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
