pipeline {
  agent any

  stages {
    stage('Clone Repo') {
      steps {
        echo 'Cloning repository...'
      }
    }

    stage('Activate venv and Install Dependencies') {
      steps {
        sh '''
          cd backend
          if [ ! -d "venv" ]; then python3 -m venv venv; fi
          . venv/bin/activate
          pip install -r requirements.txt
        '''
      }
    }

    stage('Restart Flask App using PM2') {
      steps {
        sh '''
          cd backend
          . venv/bin/activate
          pm2 restart flask-backend || pm2 start app.py --name flask-backend --interpreter ./venv/bin/python
        '''
      }
    }
  }
}

